device: cuda:0
output_directory: run_dir
log_file: train.log
print_timings: True

training:
  dspath: rmd17_aspirin_01.pkl
  batch_size: 100
  max_epochs: 1000
  nbatch_per_epoch: 10
  nbatch_per_validation: 1 
  ema_decay: 0.99
  default_loss_type: mse

  weight_decay: 1.e-4
  decay_targets: [energy]
  energy_terms: [energy]

  init_lr: 1.e-3
  lr: 2.e-3
  final_lr: 1.e-6
  loss:
    e:
      key: total_energy
      ref: formation_energy
      weight: 1.e-3
      unit: kcalpermol
    f:
      key: forces
      ref: forces
      weight: 1.
      unit: kcalpermol
      
    
model:
  cutoff: 5.1
  energy_terms: [energy]
  preprocessing:
    graph_filter_angle:
      module_name: GRAPH_FILTER
      cutoff: 3.5
      graph_key: graph
      graph_out: graph_angle
    angle_extension:
      module_name: GRAPH_ANGULAR_EXTENSION
      graph_key: graph_angle

  modules:
    embedding:
      module_name: ANI_AEV
      embedding_key: embedding
      species_order: [H,C,N,O]
      graph_key: graph
      graph_angle_key: graph_angle
      radial_eta: 19.7
      angular_eta: 12.5
      radial_dist_divisions: 16
      angular_dist_divisions: 8
      zeta: 14.1
      angle_sections: 4
      radial_start: 0.8
      angular_start: 0.8

    energy:
      module_name: CHEMICAL_NET
      species_order: [H,C,N,O]
      activation: partial(celu,alpha=0.1)
      neurons: [256,192,160,1]
      input_key: embedding
      squeeze: True
      

