[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "FeNNol"
version = "0.1"
readme = "README.md"
dependencies = [
   "numpy",
   "scipy",
   "sympy",
   "flax[all]",
]


[project.scripts]
fennol_md = "fennol.md.dynamic:main"